// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdFfzcyTPkgkaWZiRy_hKiKtLVPl5i8d0',
    appId: '1:1033099197260:web:2356f973713073176bade9',
    messagingSenderId: '1033099197260',
    projectId: 'fir-chatapp-d9fd6',
    authDomain: 'fir-chatapp-d9fd6.firebaseapp.com',
    storageBucket: 'fir-chatapp-d9fd6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LB78dLyPyYZyjjPTxttOqbCxvHPoUs4',
    appId: '1:1033099197260:android:2dff1ffc01a097186bade9',
    messagingSenderId: '1033099197260',
    projectId: 'fir-chatapp-d9fd6',
    storageBucket: 'fir-chatapp-d9fd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDNXbY0ukpdwcmcjJbrfa8Z9dJkY1EdhE',
    appId: '1:1033099197260:ios:579b9ca542ec2ade6bade9',
    messagingSenderId: '1033099197260',
    projectId: 'fir-chatapp-d9fd6',
    storageBucket: 'fir-chatapp-d9fd6.firebasestorage.app',
    iosBundleId: 'com.jobandeep.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDNXbY0ukpdwcmcjJbrfa8Z9dJkY1EdhE',
    appId: '1:1033099197260:ios:57ecca81b4348d716bade9',
    messagingSenderId: '1033099197260',
    projectId: 'fir-chatapp-d9fd6',
    storageBucket: 'fir-chatapp-d9fd6.firebasestorage.app',
    iosBundleId: 'com.jobandee.firebase-chat-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdFfzcyTPkgkaWZiRy_hKiKtLVPl5i8d0',
    appId: '1:1033099197260:web:356b5ed128a074a96bade9',
    messagingSenderId: '1033099197260',
    projectId: 'fir-chatapp-d9fd6',
    authDomain: 'fir-chatapp-d9fd6.firebaseapp.com',
    storageBucket: 'fir-chatapp-d9fd6.firebasestorage.app',
  );
}
